export const conversationsListSampleData = [
  {
    conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
    conversationTitle: "conversation_2025-06-21T06:45:20Z",
    selectedModal: "gpt-o4",
    dateTimeCreated: "2025-06-21T06:45:20Z",
    userId: "aditya.gupta@gmail.com",
    isActive: true,
    isPinned: true,
    isArchieved: false,
  },
  {
    conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
    conversationTitle: "conversation_2025-06-20T11:22:47Z",
    selectedModal: "gpt-o3",
    dateTimeCreated: "2025-06-20T11:22:47Z",
    userId: "aditya.gupta@gmail.com",
    isActive: false,
    isPinned: false,
    isArchieved: true,
  },
  {
    conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
    conversationTitle: "conversation_2025-06-19T08:04:13Z",
    selectedModal: "deepseek-r1",
    dateTimeCreated: "2025-06-19T08:04:13Z",
    userId: "aditya.gupta@gmail.com",
    isActive: false,
    isPinned: true,
    isArchieved: false,
  },
  {
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    conversationTitle: "conversation_2025-06-18T13:15:38Z",
    selectedModal: "gpt-o4",
    dateTimeCreated: "2025-06-18T13:15:38Z",
    userId: "aditya.gupta@gmail.com",
    isActive: true,
    isPinned: false,
    isArchieved: false,
  },
  {
    conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
    conversationTitle: "conversation_2025-06-17T10:51:22Z",
    selectedModal: "gpt-o3",
    dateTimeCreated: "2025-06-17T10:51:22Z",
    userId: "aditya.gupta@gmail.com",
    isActive: false,
    isPinned: false,
    isArchieved: true,
  },
  {
    conversationId: "febc3d2e-f382-432f-905c-1df111239121",
    conversationTitle: "conversation_2025-06-16T15:43:30Z",
    selectedModal: "deepseek-r1",
    dateTimeCreated: "2025-06-16T15:43:30Z",
    userId: "aditya.gupta@gmail.com",
    isActive: false,
    isPinned: true,
    isArchieved: false,
  },
  {
    conversationId: "af12accc-88b6-4af1-b3b0-7c43219312a2",
    conversationTitle: "conversation_2025-06-15T07:10:01Z",
    selectedModal: "gpt-o3",
    dateTimeCreated: "2025-06-15T07:10:01Z",
    userId: "aditya.gupta@gmail.com",
    isActive: true,
    isPinned: false,
    isArchieved: false,
  },
  {
    conversationId: "d8ec54ee-a8c4-4d32-9aa8-ec64beec015e",
    conversationTitle: "conversation_2025-06-14T04:40:59Z",
    selectedModal: "gpt-o4",
    dateTimeCreated: "2025-06-14T04:40:59Z",
    userId: "aditya.gupta@gmail.com",
    isActive: false,
    isPinned: false,
    isArchieved: true,
  },
  {
    conversationId: "05bc2a5a-9b6c-4224-a9b2-35cc70197ee4",
    conversationTitle: "conversation_2025-06-13T12:33:17Z",
    selectedModal: "deepseek-r1",
    dateTimeCreated: "2025-06-13T12:33:17Z",
    userId: "aditya.gupta@gmail.com",
    isActive: true,
    isPinned: true,
    isArchieved: false,
  },
  {
    conversationId: "e0033c67-84cd-485f-9a52-9931d5b8d5a4",
    conversationTitle: "conversation_2025-06-12T09:20:49Z",
    selectedModal: "gpt-o3",
    dateTimeCreated: "2025-06-12T09:20:49Z",
    userId: "aditya.gupta@gmail.com",
    isActive: false,
    isPinned: false,
    isArchieved: false,
  },
  {
    conversationId: "a9e03db5-2e03-4eec-926a-fbfe96f255cb",
    conversationTitle: "conversation_2025-06-11T17:08:10Z",
    selectedModal: "gpt-o4",
    dateTimeCreated: "2025-06-11T17:08:10Z",
    userId: "aditya.gupta@gmail.com",
    isActive: false,
    isPinned: true,
    isArchieved: false,
  },
  {
    conversationId: "c6d569b0-759f-481e-8757-d9aabff4de7c",
    conversationTitle: "conversation_2025-06-10T06:41:23Z",
    selectedModal: "deepseek-r1",
    dateTimeCreated: "2025-06-10T06:41:23Z",
    userId: "aditya.gupta@gmail.com",
    isActive: true,
    isPinned: false,
    isArchieved: false,
  },
  {
    conversationId: "f3a1b47c-bd6a-44fc-9b3d-d70fb6cf0f42",
    conversationTitle: "conversation_2025-06-09T14:25:07Z",
    selectedModal: "gpt-o3",
    dateTimeCreated: "2025-06-09T14:25:07Z",
    userId: "aditya.gupta@gmail.com",
    isActive: false,
    isPinned: false,
    isArchieved: true,
  },
  {
    conversationId: "b192350d-263f-4e03-b13c-994a9c45e3d4",
    conversationTitle: "conversation_2025-06-08T10:05:55Z",
    selectedModal: "gpt-o4",
    dateTimeCreated: "2025-06-08T10:05:55Z",
    userId: "aditya.gupta@gmail.com",
    isActive: true,
    isPinned: false,
    isArchieved: false,
  },
  {
    conversationId: "0a1653bb-8c9c-40e4-841b-a39f1807d938",
    conversationTitle: "conversation_2025-06-07T08:56:38Z",
    selectedModal: "deepseek-r1",
    dateTimeCreated: "2025-06-07T08:56:38Z",
    userId: "aditya.gupta@gmail.com",
    isActive: false,
    isPinned: false,
    isArchieved: true,
  },
];

export const messagesListSampleData = [
  {
    messageId: "88b15c49-a2c2-43e9-a8b5-a8760d588601",
    conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "How can I integrate speech-to-text in my chatbot?",
    messageDateTimeCreated: "2025-06-21T06:46:00Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Querying about voice integration options",
    messageAdditionalInfo: {
      tableData: [],
      chartData: [],
      extra: {},
    },
  },
  {
    messageId: "ab4c1452-1547-43b1-a99e-0c446c08c930",
    conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "You can use Web Speech API or integrate Whisper for better accuracy.",
    messageDateTimeCreated: "2025-06-20T11:23:10Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Suggested options for speech input",
    messageAdditionalInfo: {
      tableData: [],
      chartData: [],
      extra: {},
    },
  },
  {
    messageId: "f2945ea7-2937-4e7a-a725-08e23848f20d",
    conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
    messageType: "Modal",
    messageAvatarSrc: "logo",
    messageDescription: "Generating a response using deepseek-r1...",
    messageDateTimeCreated: "2025-06-19T08:04:18Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "System processing the user prompt",
    messageAdditionalInfo: {
      tableData: [],
      chartData: [],
      extra: {},
    },
  },
  {
    messageId: "7fb3c7b0-32f7-4ca6-b3d5-b39546ec338f",
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Show me a list of recent MongoDB queries I executed.",
    messageDateTimeCreated: "2025-06-18T13:16:09Z",
    isEdited: true,
    referenceMessageId: "a12e4bfa-f4ae-43b9-9ef1-b58b1e6a742b",
    messageSubDescription: "Refined version of previous query",
    messageAdditionalInfo: {
      tableData: [],
      chartData: [],
      extra: {},
    },
  },
  {
    messageId: "a12e4bfa-f4ae-43b9-9ef1-b58b1e6a742b",
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "MongoDB queries?",
    messageDateTimeCreated: "2025-06-18T13:15:54Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Initial vague query",
    messageAdditionalInfo: {
      tableData: [],
      chartData: [],
      extra: {},
    },
  },
  {
    messageId: "f7857504-2170-4bcf-87b7-9902c8dc68f4",
    conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Here’s a breakdown of your API request performance over the last 24h.",
    messageDateTimeCreated: "2025-06-17T10:52:01Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Performance diagnostics summary",
    messageAdditionalInfo: {
      tableData: [
        { time: "02:00", latency: "120ms" },
        { time: "08:00", latency: "95ms" },
      ],
      chartData: [],
      extra: {},
    },
  },
];

export const messagesList1SampleData = [
  {
    messageId: "101",
    conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "How do I store user sessions in FastAPI?",
    messageDateTimeCreated: "2025-06-21T07:01:00Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "User asking about session storage",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "102",
    conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Use server-side Redis or secure cookies for session management.",
    messageDateTimeCreated: "2025-06-21T07:01:10Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Suggested methods for storing sessions",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "103",
    conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Can I use JWT instead?",
    messageDateTimeCreated: "2025-06-21T07:01:20Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Exploring JWT alternative",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "104",
    conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Yes, JWT is great for stateless auth. Just be cautious with token expiration and refresh logic.",
    messageDateTimeCreated: "2025-06-21T07:01:30Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "JWT pros and best practices",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "105",
    conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "What about session hijacking risks?",
    messageDateTimeCreated: "2025-06-21T07:01:40Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Security concern raised",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "106",
    conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Use HTTPS, rotating secrets, and token invalidation on logout to mitigate that.",
    messageDateTimeCreated: "2025-06-21T07:01:50Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Mitigation strategies shared",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },

  {
    messageId: "201",
    conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "How do I render a dynamic SVG graph?",
    messageDateTimeCreated: "2025-06-20T11:00:00Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Graph rendering inquiry",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "202",
    conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Try using D3.js or SVG.js for DOM manipulation of SVG elements.",
    messageDateTimeCreated: "2025-06-20T11:00:15Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Suggested libraries for SVG handling",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "203",
    conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Which one has better animation support?",
    messageDateTimeCreated: "2025-06-20T11:00:30Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Clarification on animation capabilities",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "204",
    conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "SVG.js offers easier animation chaining; D3.js gives fine control but has a steeper learning curve.",
    messageDateTimeCreated: "2025-06-20T11:00:45Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Comparison of animation libraries",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "205",
    conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Thanks, I’ll try SVG.js first.",
    messageDateTimeCreated: "2025-06-20T11:00:55Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Closing the thread",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "206",
    conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription: "Perfect choice for quick SVG prototyping!",
    messageDateTimeCreated: "2025-06-20T11:01:10Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Encouragement from Bot",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "301",
    conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription:
      "What’s the best way to implement buffer memory in a chatbot?",
    messageDateTimeCreated: "2025-06-19T08:05:00Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Querying about context retention",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "302",
    conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Use a conversation history cache keyed by user ID to track recent exchanges.",
    messageDateTimeCreated: "2025-06-19T08:05:10Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Basic memory implementation advice",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "303",
    conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Should I use Redis or in-memory caching?",
    messageDateTimeCreated: "2025-06-19T08:05:20Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Asking about storage mechanism",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "304",
    conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Redis is ideal for scalability; in-memory is faster for local dev/testing.",
    messageDateTimeCreated: "2025-06-19T08:05:30Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Trade-offs between storage options",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "305",
    conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Is there a way to add role-based turns in memory too?",
    messageDateTimeCreated: "2025-06-19T08:05:40Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Multi-turn memory with roles",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "306",
    conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Yes! Structure your memory like a sequence of {'role': 'user/bot', 'content': '...'} items.",
    messageDateTimeCreated: "2025-06-19T08:05:55Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Describing memory role structure",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "401",
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "How do I log MongoDB query performance?",
    messageDateTimeCreated: "2025-06-18T13:20:00Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Performance logging",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "402",
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Use MongoDB’s profiler or enable `explain()` to analyze slow queries.",
    messageDateTimeCreated: "2025-06-18T13:20:10Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Logging tools for query tracing",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "403",
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Can I export profiler data?",
    messageDateTimeCreated: "2025-06-18T13:20:25Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Persistence of profiling data",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "404",
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Yes—query the `system.profile` collection and export as JSON or CSV.",
    messageDateTimeCreated: "2025-06-18T13:20:40Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Export method suggested",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "405",
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "What’s a good query time threshold for alerts?",
    messageDateTimeCreated: "2025-06-18T13:20:55Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Alert configuration",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "406",
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Typically, anything over 100ms is worth investigating—depending on your workload.",
    messageDateTimeCreated: "2025-06-18T13:21:10Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Latency threshold guidance",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "501",
    conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Show me how to animate an SVG icon with CSS.",
    messageDateTimeCreated: "2025-06-17T10:55:00Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "SVG animation inquiry",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "502",
    conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "You can use CSS keyframes on SVG paths, circles, or transforms for animations.",
    messageDateTimeCreated: "2025-06-17T10:55:15Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Explaining how CSS animates SVGs",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "503",
    conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Do I need to use classes or inline styles?",
    messageDateTimeCreated: "2025-06-17T10:55:30Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Implementation clarification",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "504",
    conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Using classes is preferred—it separates style from structure and is easier to maintain.",
    messageDateTimeCreated: "2025-06-17T10:55:45Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Best practice advice",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "505",
    conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Got it. Can I animate stroke width too?",
    messageDateTimeCreated: "2025-06-17T10:56:00Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Question about stroke animation",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "506",
    conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Yes! You can animate `stroke-width` using keyframes or CSS transitions.",
    messageDateTimeCreated: "2025-06-17T10:56:15Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Confirming stroke animation capability",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },

  // Three more conversations like this follow...
];

export const messagesList2SampleData = [
  {
    conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
    messages: [
      {
        messageId: "101",
        conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "How do I store user sessions in FastAPI?",
        messageDateTimeCreated: "2025-06-21T07:01:00Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "User asking about session storage",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "102",
        conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Use server-side Redis or secure cookies for session management.",
        messageDateTimeCreated: "2025-06-21T07:01:10Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Suggested methods for storing sessions",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "103",
        conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "Can I use JWT instead?",
        messageDateTimeCreated: "2025-06-21T07:01:20Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Exploring JWT alternative",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "104",
        conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Yes, JWT is great for stateless auth. Just be cautious with token expiration and refresh logic.",
        messageDateTimeCreated: "2025-06-21T07:01:30Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "JWT pros and best practices",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "105",
        conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "What about session hijacking risks?",
        messageDateTimeCreated: "2025-06-21T07:01:40Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Security concern raised",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "106",
        conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Use HTTPS, rotating secrets, and token invalidation on logout to mitigate that.",
        messageDateTimeCreated: "2025-06-21T07:01:50Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Mitigation strategies shared",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
    ],
  },
  {
    conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
    messages: [
      {
        messageId: "201",
        conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "How do I render a dynamic SVG graph?",
        messageDateTimeCreated: "2025-06-20T11:00:00Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Graph rendering inquiry",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "202",
        conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Try using D3.js or SVG.js for DOM manipulation of SVG elements.",
        messageDateTimeCreated: "2025-06-20T11:00:15Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Suggested libraries for SVG handling",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "203",
        conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "Which one has better animation support?",
        messageDateTimeCreated: "2025-06-20T11:00:30Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Clarification on animation capabilities",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "204",
        conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "SVG.js offers easier animation chaining; D3.js gives fine control but has a steeper learning curve.",
        messageDateTimeCreated: "2025-06-20T11:00:45Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Comparison of animation libraries",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "205",
        conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "Thanks, I’ll try SVG.js first.",
        messageDateTimeCreated: "2025-06-20T11:00:55Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Closing the thread",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "206",
        conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription: "Perfect choice for quick SVG prototyping!",
        messageDateTimeCreated: "2025-06-20T11:01:10Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Encouragement from Bot",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
    ],
  },
  {
    conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
    messages: [
      {
        messageId: "301",
        conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription:
          "What’s the best way to implement buffer memory in a chatbot?",
        messageDateTimeCreated: "2025-06-19T08:05:00Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Querying about context retention",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "302",
        conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Use a conversation history cache keyed by user ID to track recent exchanges.",
        messageDateTimeCreated: "2025-06-19T08:05:10Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Basic memory implementation advice",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "303",
        conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "Should I use Redis or in-memory caching?",
        messageDateTimeCreated: "2025-06-19T08:05:20Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Asking about storage mechanism",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "304",
        conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Redis is ideal for scalability; in-memory is faster for local dev/testing.",
        messageDateTimeCreated: "2025-06-19T08:05:30Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Trade-offs between storage options",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "305",
        conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription:
          "Is there a way to add role-based turns in memory too?",
        messageDateTimeCreated: "2025-06-19T08:05:40Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Multi-turn memory with roles",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "306",
        conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Yes! Structure your memory like a sequence of {'role': 'user/bot', 'content': '...'} items.",
        messageDateTimeCreated: "2025-06-19T08:05:55Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Describing memory role structure",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
    ],
  },
  {
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    messages: [
      {
        messageId: "401",
        conversationId: "42688556-a921-4db8-9260-40b83153f94c",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "How do I log MongoDB query performance?",
        messageDateTimeCreated: "2025-06-18T13:20:00Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Performance logging",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "402",
        conversationId: "42688556-a921-4db8-9260-40b83153f94c",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Use MongoDB’s profiler or enable `explain()` to analyze slow queries.",
        messageDateTimeCreated: "2025-06-18T13:20:10Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Logging tools for query tracing",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "403",
        conversationId: "42688556-a921-4db8-9260-40b83153f94c",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "Can I export profiler data?",
        messageDateTimeCreated: "2025-06-18T13:20:25Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Persistence of profiling data",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "404",
        conversationId: "42688556-a921-4db8-9260-40b83153f94c",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Yes—query the `system.profile` collection and export as JSON or CSV.",
        messageDateTimeCreated: "2025-06-18T13:20:40Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Export method suggested",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "405",
        conversationId: "42688556-a921-4db8-9260-40b83153f94c",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "What’s a good query time threshold for alerts?",
        messageDateTimeCreated: "2025-06-18T13:20:55Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Alert configuration",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "406",
        conversationId: "42688556-a921-4db8-9260-40b83153f94c",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Typically, anything over 100ms is worth investigating—depending on your workload.",
        messageDateTimeCreated: "2025-06-18T13:21:10Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Latency threshold guidance",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
    ],
  },
  {
    conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
    messages: [
      {
        messageId: "501",
        conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "Show me how to animate an SVG icon with CSS.",
        messageDateTimeCreated: "2025-06-17T10:55:00Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "SVG animation inquiry",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "502",
        conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "You can use CSS keyframes on SVG paths, circles, or transforms for animations.",
        messageDateTimeCreated: "2025-06-17T10:55:15Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Explaining how CSS animates SVGs",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "503",
        conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "Do I need to use classes or inline styles?",
        messageDateTimeCreated: "2025-06-17T10:55:30Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Implementation clarification",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "504",
        conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Using classes is preferred—it separates style from structure and is easier to maintain.",
        messageDateTimeCreated: "2025-06-17T10:55:45Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Best practice advice",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "505",
        conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "Got it. Can I animate stroke width too?",
        messageDateTimeCreated: "2025-06-17T10:56:00Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Question about stroke animation",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "506",
        conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Yes! You can animate `stroke-width` using keyframes or CSS transitions.",
        messageDateTimeCreated: "2025-06-17T10:56:15Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Confirming stroke animation capability",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
    ],
  },
];
