export const conversationsListSampleData = [
  {
    conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
    conversationTitle: "conversation_2025-06-21T06:45:20Z",
    selectedModal: "gpt-o4",
    dateTimeCreated: "2025-06-21T06:45:20Z",
    userId: "aditya.gupta@gmail.com",
    isActive: true,
    isPinned: true,
    isArchieved: false,
  },
  {
    conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
    conversationTitle: "conversation_2025-06-20T11:22:47Z",
    selectedModal: "gpt-o3",
    dateTimeCreated: "2025-06-20T11:22:47Z",
    userId: "aditya.gupta@gmail.com",
    isActive: false,
    isPinned: false,
    isArchieved: true,
  },
  {
    conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
    conversationTitle: "conversation_2025-06-19T08:04:13Z",
    selectedModal: "deepseek-r1",
    dateTimeCreated: "2025-06-19T08:04:13Z",
    userId: "aditya.gupta@gmail.com",
    isActive: false,
    isPinned: true,
    isArchieved: false,
  },
  {
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    conversationTitle: "conversation_2025-06-18T13:15:38Z",
    selectedModal: "gpt-o4",
    dateTimeCreated: "2025-06-18T13:15:38Z",
    userId: "aditya.gupta@gmail.com",
    isActive: true,
    isPinned: false,
    isArchieved: false,
  },
  {
    conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
    conversationTitle: "conversation_2025-06-17T10:51:22Z",
    selectedModal: "gpt-o3",
    dateTimeCreated: "2025-06-17T10:51:22Z",
    userId: "aditya.gupta@gmail.com",
    isActive: false,
    isPinned: false,
    isArchieved: true,
  },
  {
    conversationId: "febc3d2e-f382-432f-905c-1df111239121",
    conversationTitle: "conversation_2025-06-16T15:43:30Z",
    selectedModal: "deepseek-r1",
    dateTimeCreated: "2025-06-16T15:43:30Z",
    userId: "aditya.gupta@gmail.com",
    isActive: false,
    isPinned: true,
    isArchieved: false,
  },
  {
    conversationId: "af12accc-88b6-4af1-b3b0-7c43219312a2",
    conversationTitle: "conversation_2025-06-15T07:10:01Z",
    selectedModal: "gpt-o3",
    dateTimeCreated: "2025-06-15T07:10:01Z",
    userId: "aditya.gupta@gmail.com",
    isActive: true,
    isPinned: false,
    isArchieved: false,
  },
  {
    conversationId: "d8ec54ee-a8c4-4d32-9aa8-ec64beec015e",
    conversationTitle: "conversation_2025-06-14T04:40:59Z",
    selectedModal: "gpt-o4",
    dateTimeCreated: "2025-06-14T04:40:59Z",
    userId: "aditya.gupta@gmail.com",
    isActive: false,
    isPinned: false,
    isArchieved: true,
  },
  {
    conversationId: "05bc2a5a-9b6c-4224-a9b2-35cc70197ee4",
    conversationTitle: "conversation_2025-06-13T12:33:17Z",
    selectedModal: "deepseek-r1",
    dateTimeCreated: "2025-06-13T12:33:17Z",
    userId: "aditya.gupta@gmail.com",
    isActive: true,
    isPinned: true,
    isArchieved: false,
  },
  {
    conversationId: "e0033c67-84cd-485f-9a52-9931d5b8d5a4",
    conversationTitle: "conversation_2025-06-12T09:20:49Z",
    selectedModal: "gpt-o3",
    dateTimeCreated: "2025-06-12T09:20:49Z",
    userId: "aditya.gupta@gmail.com",
    isActive: false,
    isPinned: false,
    isArchieved: false,
  },
  {
    conversationId: "a9e03db5-2e03-4eec-926a-fbfe96f255cb",
    conversationTitle: "conversation_2025-06-11T17:08:10Z",
    selectedModal: "gpt-o4",
    dateTimeCreated: "2025-06-11T17:08:10Z",
    userId: "aditya.gupta@gmail.com",
    isActive: false,
    isPinned: true,
    isArchieved: false,
  },
  {
    conversationId: "c6d569b0-759f-481e-8757-d9aabff4de7c",
    conversationTitle: "conversation_2025-06-10T06:41:23Z",
    selectedModal: "deepseek-r1",
    dateTimeCreated: "2025-06-10T06:41:23Z",
    userId: "aditya.gupta@gmail.com",
    isActive: true,
    isPinned: false,
    isArchieved: false,
  },
  {
    conversationId: "f3a1b47c-bd6a-44fc-9b3d-d70fb6cf0f42",
    conversationTitle: "conversation_2025-06-09T14:25:07Z",
    selectedModal: "gpt-o3",
    dateTimeCreated: "2025-06-09T14:25:07Z",
    userId: "aditya.gupta@gmail.com",
    isActive: false,
    isPinned: false,
    isArchieved: true,
  },
  {
    conversationId: "b192350d-263f-4e03-b13c-994a9c45e3d4",
    conversationTitle: "conversation_2025-06-08T10:05:55Z",
    selectedModal: "gpt-o4",
    dateTimeCreated: "2025-06-08T10:05:55Z",
    userId: "aditya.gupta@gmail.com",
    isActive: true,
    isPinned: false,
    isArchieved: false,
  },
  {
    conversationId: "0a1653bb-8c9c-40e4-841b-a39f1807d938",
    conversationTitle: "conversation_2025-06-07T08:56:38Z",
    selectedModal: "deepseek-r1",
    dateTimeCreated: "2025-06-07T08:56:38Z",
    userId: "aditya.gupta@gmail.com",
    isActive: false,
    isPinned: false,
    isArchieved: true,
  },
];

export const messagesListSampleData = [
  {
    messageId: "88b15c49-a2c2-43e9-a8b5-a8760d588601",
    conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "How can I integrate speech-to-text in my chatbot?",
    messageDateTimeCreated: "2025-06-21T06:46:00Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Querying about voice integration options",
    messageAdditionalInfo: {
      tableData: [],
      chartData: [],
      extra: {},
    },
  },
  {
    messageId: "ab4c1452-1547-43b1-a99e-0c446c08c930",
    conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "You can use Web Speech API or integrate Whisper for better accuracy.",
    messageDateTimeCreated: "2025-06-20T11:23:10Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Suggested options for speech input",
    messageAdditionalInfo: {
      tableData: [],
      chartData: [],
      extra: {},
    },
  },
  {
    messageId: "f2945ea7-2937-4e7a-a725-08e23848f20d",
    conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
    messageType: "Modal",
    messageAvatarSrc: "logo",
    messageDescription: "Generating a response using deepseek-r1...",
    messageDateTimeCreated: "2025-06-19T08:04:18Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "System processing the user prompt",
    messageAdditionalInfo: {
      tableData: [],
      chartData: [],
      extra: {},
    },
  },
  {
    messageId: "7fb3c7b0-32f7-4ca6-b3d5-b39546ec338f",
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Show me a list of recent MongoDB queries I executed.",
    messageDateTimeCreated: "2025-06-18T13:16:09Z",
    isEdited: true,
    referenceMessageId: "a12e4bfa-f4ae-43b9-9ef1-b58b1e6a742b",
    messageSubDescription: "Refined version of previous query",
    messageAdditionalInfo: {
      tableData: [],
      chartData: [],
      extra: {},
    },
  },
  {
    messageId: "a12e4bfa-f4ae-43b9-9ef1-b58b1e6a742b",
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "MongoDB queries?",
    messageDateTimeCreated: "2025-06-18T13:15:54Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Initial vague query",
    messageAdditionalInfo: {
      tableData: [],
      chartData: [],
      extra: {},
    },
  },
  {
    messageId: "f7857504-2170-4bcf-87b7-9902c8dc68f4",
    conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Here’s a breakdown of your API request performance over the last 24h.",
    messageDateTimeCreated: "2025-06-17T10:52:01Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Performance diagnostics summary",
    messageAdditionalInfo: {
      tableData: [
        { time: "02:00", latency: "120ms" },
        { time: "08:00", latency: "95ms" },
      ],
      chartData: [],
      extra: {},
    },
  },
];

export const messagesList1SampleData = [
  {
    messageId: "101",
    conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "How do I store user sessions in FastAPI?",
    messageDateTimeCreated: "2025-06-21T07:01:00Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "User asking about session storage",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "102",
    conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Use server-side Redis or secure cookies for session management.",
    messageDateTimeCreated: "2025-06-21T07:01:10Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Suggested methods for storing sessions",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "103",
    conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Can I use JWT instead?",
    messageDateTimeCreated: "2025-06-21T07:01:20Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Exploring JWT alternative",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "104",
    conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Yes, JWT is great for stateless auth. Just be cautious with token expiration and refresh logic.",
    messageDateTimeCreated: "2025-06-21T07:01:30Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "JWT pros and best practices",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "105",
    conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "What about session hijacking risks?",
    messageDateTimeCreated: "2025-06-21T07:01:40Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Security concern raised",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "106",
    conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Use HTTPS, rotating secrets, and token invalidation on logout to mitigate that.",
    messageDateTimeCreated: "2025-06-21T07:01:50Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Mitigation strategies shared",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },

  {
    messageId: "201",
    conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "How do I render a dynamic SVG graph?",
    messageDateTimeCreated: "2025-06-20T11:00:00Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Graph rendering inquiry",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "202",
    conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Try using D3.js or SVG.js for DOM manipulation of SVG elements.",
    messageDateTimeCreated: "2025-06-20T11:00:15Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Suggested libraries for SVG handling",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "203",
    conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Which one has better animation support?",
    messageDateTimeCreated: "2025-06-20T11:00:30Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Clarification on animation capabilities",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "204",
    conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "SVG.js offers easier animation chaining; D3.js gives fine control but has a steeper learning curve.",
    messageDateTimeCreated: "2025-06-20T11:00:45Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Comparison of animation libraries",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "205",
    conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Thanks, I’ll try SVG.js first.",
    messageDateTimeCreated: "2025-06-20T11:00:55Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Closing the thread",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "206",
    conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription: "Perfect choice for quick SVG prototyping!",
    messageDateTimeCreated: "2025-06-20T11:01:10Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Encouragement from Bot",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "301",
    conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription:
      "What’s the best way to implement buffer memory in a chatbot?",
    messageDateTimeCreated: "2025-06-19T08:05:00Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Querying about context retention",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "302",
    conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Use a conversation history cache keyed by user ID to track recent exchanges.",
    messageDateTimeCreated: "2025-06-19T08:05:10Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Basic memory implementation advice",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "303",
    conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Should I use Redis or in-memory caching?",
    messageDateTimeCreated: "2025-06-19T08:05:20Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Asking about storage mechanism",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "304",
    conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Redis is ideal for scalability; in-memory is faster for local dev/testing.",
    messageDateTimeCreated: "2025-06-19T08:05:30Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Trade-offs between storage options",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "305",
    conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Is there a way to add role-based turns in memory too?",
    messageDateTimeCreated: "2025-06-19T08:05:40Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Multi-turn memory with roles",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "306",
    conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Yes! Structure your memory like a sequence of {'role': 'user/bot', 'content': '...'} items.",
    messageDateTimeCreated: "2025-06-19T08:05:55Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Describing memory role structure",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "401",
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "How do I log MongoDB query performance?",
    messageDateTimeCreated: "2025-06-18T13:20:00Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Performance logging",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "402",
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Use MongoDB’s profiler or enable `explain()` to analyze slow queries.",
    messageDateTimeCreated: "2025-06-18T13:20:10Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Logging tools for query tracing",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "403",
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Can I export profiler data?",
    messageDateTimeCreated: "2025-06-18T13:20:25Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Persistence of profiling data",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "404",
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Yes—query the `system.profile` collection and export as JSON or CSV.",
    messageDateTimeCreated: "2025-06-18T13:20:40Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Export method suggested",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "405",
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "What’s a good query time threshold for alerts?",
    messageDateTimeCreated: "2025-06-18T13:20:55Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Alert configuration",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "406",
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Typically, anything over 100ms is worth investigating—depending on your workload.",
    messageDateTimeCreated: "2025-06-18T13:21:10Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Latency threshold guidance",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "501",
    conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Show me how to animate an SVG icon with CSS.",
    messageDateTimeCreated: "2025-06-17T10:55:00Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "SVG animation inquiry",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "502",
    conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "You can use CSS keyframes on SVG paths, circles, or transforms for animations.",
    messageDateTimeCreated: "2025-06-17T10:55:15Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Explaining how CSS animates SVGs",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "503",
    conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Do I need to use classes or inline styles?",
    messageDateTimeCreated: "2025-06-17T10:55:30Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Implementation clarification",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "504",
    conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Using classes is preferred—it separates style from structure and is easier to maintain.",
    messageDateTimeCreated: "2025-06-17T10:55:45Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Best practice advice",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "505",
    conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
    messageType: "User",
    messageAvatarSrc: "logo",
    messageDescription: "Got it. Can I animate stroke width too?",
    messageDateTimeCreated: "2025-06-17T10:56:00Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Question about stroke animation",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },
  {
    messageId: "506",
    conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
    messageType: "Bot",
    messageAvatarSrc: "logo",
    messageDescription:
      "Yes! You can animate `stroke-width` using keyframes or CSS transitions.",
    messageDateTimeCreated: "2025-06-17T10:56:15Z",
    isEdited: false,
    referenceMessageId: null,
    messageSubDescription: "Confirming stroke animation capability",
    messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
  },

  // Three more conversations like this follow...
];

export const messagesList2SampleData = [
  {
    conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
    messages: [
      {
        messageId: "101",
        conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "How do I store user sessions in FastAPI?",
        messageDateTimeCreated: "2025-06-21T07:01:00Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "User asking about session storage",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "102",
        conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Use server-side Redis or secure cookies for session management.",
        messageDateTimeCreated: "2025-06-21T07:01:10Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Suggested methods for storing sessions",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "103",
        conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "Can I use JWT instead?",
        messageDateTimeCreated: "2025-06-21T07:01:20Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Exploring JWT alternative",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "104",
        conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Yes, JWT is great for stateless auth. Just be cautious with token expiration and refresh logic.",
        messageDateTimeCreated: "2025-06-21T07:01:30Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "JWT pros and best practices",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "105",
        conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "What about session hijacking risks?",
        messageDateTimeCreated: "2025-06-21T07:01:40Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Security concern raised",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "106",
        conversationId: "9be2c4af-e3de-4ae1-9f7a-dde8445a613b",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Use HTTPS, rotating secrets, and token invalidation on logout to mitigate that.",
        messageDateTimeCreated: "2025-06-21T07:01:50Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Mitigation strategies shared",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
    ],
  },
  {
    conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
    messages: [
      {
        messageId: "201",
        conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "How do I render a dynamic SVG graph?",
        messageDateTimeCreated: "2025-06-20T11:00:00Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Graph rendering inquiry",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "202",
        conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Try using D3.js or SVG.js for DOM manipulation of SVG elements.",
        messageDateTimeCreated: "2025-06-20T11:00:15Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Suggested libraries for SVG handling",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "203",
        conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "Which one has better animation support?",
        messageDateTimeCreated: "2025-06-20T11:00:30Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Clarification on animation capabilities",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "204",
        conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "SVG.js offers easier animation chaining; D3.js gives fine control but has a steeper learning curve.",
        messageDateTimeCreated: "2025-06-20T11:00:45Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Comparison of animation libraries",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "205",
        conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "Thanks, I’ll try SVG.js first.",
        messageDateTimeCreated: "2025-06-20T11:00:55Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Closing the thread",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "206",
        conversationId: "3f4c7299-0e75-4da1-91b4-b170ab3b5cc0",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription: "Perfect choice for quick SVG prototyping!",
        messageDateTimeCreated: "2025-06-20T11:01:10Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Encouragement from Bot",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
    ],
  },
  {
    conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
    messages: [
      {
        messageId: "301",
        conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription:
          "What’s the best way to implement buffer memory in a chatbot?",
        messageDateTimeCreated: "2025-06-19T08:05:00Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Querying about context retention",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "302",
        conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Use a conversation history cache keyed by user ID to track recent exchanges.",
        messageDateTimeCreated: "2025-06-19T08:05:10Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Basic memory implementation advice",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "303",
        conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "Should I use Redis or in-memory caching?",
        messageDateTimeCreated: "2025-06-19T08:05:20Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Asking about storage mechanism",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "304",
        conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Redis is ideal for scalability; in-memory is faster for local dev/testing.",
        messageDateTimeCreated: "2025-06-19T08:05:30Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Trade-offs between storage options",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "305",
        conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription:
          "Is there a way to add role-based turns in memory too?",
        messageDateTimeCreated: "2025-06-19T08:05:40Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Multi-turn memory with roles",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "306",
        conversationId: "117c7aaf-63c1-4462-95ee-10fc392ca93e",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Yes! Structure your memory like a sequence of {'role': 'user/bot', 'content': '...'} items.",
        messageDateTimeCreated: "2025-06-19T08:05:55Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Describing memory role structure",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
    ],
  },
  {
    conversationId: "42688556-a921-4db8-9260-40b83153f94c",
    messages: [
      {
        messageId: "401",
        conversationId: "42688556-a921-4db8-9260-40b83153f94c",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "How do I log MongoDB query performance?",
        messageDateTimeCreated: "2025-06-18T13:20:00Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Performance logging",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "402",
        conversationId: "42688556-a921-4db8-9260-40b83153f94c",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Use MongoDB’s profiler or enable `explain()` to analyze slow queries.",
        messageDateTimeCreated: "2025-06-18T13:20:10Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Logging tools for query tracing",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "403",
        conversationId: "42688556-a921-4db8-9260-40b83153f94c",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "Can I export profiler data?",
        messageDateTimeCreated: "2025-06-18T13:20:25Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Persistence of profiling data",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "404",
        conversationId: "42688556-a921-4db8-9260-40b83153f94c",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Yes—query the `system.profile` collection and export as JSON or CSV.",
        messageDateTimeCreated: "2025-06-18T13:20:40Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Export method suggested",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "405",
        conversationId: "42688556-a921-4db8-9260-40b83153f94c",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "What’s a good query time threshold for alerts?",
        messageDateTimeCreated: "2025-06-18T13:20:55Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Alert configuration",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "406",
        conversationId: "42688556-a921-4db8-9260-40b83153f94c",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Typically, anything over 100ms is worth investigating—depending on your workload.",
        messageDateTimeCreated: "2025-06-18T13:21:10Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Latency threshold guidance",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
    ],
  },
  {
    conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
    messages: [
      {
        messageId: "501",
        conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "Show me how to animate an SVG icon with CSS.",
        messageDateTimeCreated: "2025-06-17T10:55:00Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "SVG animation inquiry",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "502",
        conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "You can use CSS keyframes on SVG paths, circles, or transforms for animations.",
        messageDateTimeCreated: "2025-06-17T10:55:15Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Explaining how CSS animates SVGs",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "503",
        conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "Do I need to use classes or inline styles?",
        messageDateTimeCreated: "2025-06-17T10:55:30Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Implementation clarification",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "504",
        conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Using classes is preferred—it separates style from structure and is easier to maintain.",
        messageDateTimeCreated: "2025-06-17T10:55:45Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Best practice advice",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "505",
        conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
        messageType: "User",
        messageAvatarSrc: "logo",
        messageDescription: "Got it. Can I animate stroke width too?",
        messageDateTimeCreated: "2025-06-17T10:56:00Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Question about stroke animation",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
      {
        messageId: "506",
        conversationId: "edcfb51b-7f2e-4f91-b076-a4c54dd16b94",
        messageType: "Bot",
        messageAvatarSrc: "logo",
        messageDescription:
          "Yes! You can animate `stroke-width` using keyframes or CSS transitions.",
        messageDateTimeCreated: "2025-06-17T10:56:15Z",
        isEdited: false,
        referenceMessageId: null,
        messageSubDescription: "Confirming stroke animation capability",
        messageAdditionalInfo: { tableData: [], chartData: [], extra: {} },
      },
    ],
  },
  {
  "conversationId": "febc3d2e-f382-432f-905c-1df111239121",
  "messages": [
    {
      "messageId": "601",
      "messageType": "User",
      "messageAvatarSrc": "logo",
      "messageDescription": "How has India transformed in terms of infrastructure, education, and technology in the past two decades? I'm particularly curious about rural development and digital penetration in Tier 2/3 cities.",
      "messageDateTimeCreated": "2025-06-21T13:12:00Z",
      "isEdited": false,
      "referenceMessageId": null,
      "messageSubDescription": "User asked about India's progress",
      "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
    },
    {
      "messageId": "602",
      "messageType": "Bot",
      "messageAvatarSrc": "logo",
      "messageDescription": "Over the last 20 years, India has undergone a phenomenal transformation across several critical sectors. From the launch of Digital India to aggressive rural electrification and the development of smart cities, change has rippled through every layer of society. Broadband penetration has brought small-town economies online, empowering millions of first-generation internet users to access banking, learning, and e-commerce. In parallel, India's education sector has embraced online learning platforms, while technical skilling centers have mushroomed across the country through initiatives like Skill India. Rural infrastructure—including roads, sanitation, and affordable housing—has seen massive central investments, closing the accessibility gap. Even agricultural communities now access crop data and subsidies digitally, dramatically improving yield and income certainty.",
      "messageDateTimeCreated": "2025-06-21T13:12:15Z",
      "isEdited": false,
      "referenceMessageId": null,
      "messageSubDescription": "Bot gave high-level analysis of India's growth",
      "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
    },
    {
      "messageId": "603",
      "messageType": "User",
      "messageAvatarSrc": "logo",
      "messageDescription": "How is this change visible in the lives of ordinary citizens?",
      "messageDateTimeCreated": "2025-06-21T13:12:30Z",
      "isEdited": false,
      "referenceMessageId": null,
      "messageSubDescription": "User asked about on-ground impact",
      "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
    },
    {
      "messageId": "604",
      "messageType": "Bot",
      "messageAvatarSrc": "logo",
      "messageDescription": "From a villager paying bills using a mobile wallet to students in rural Tamil Nadu accessing coding classes via YouTube, the impact is measurable and emotional. Small business owners in remote parts of Uttar Pradesh now receive digital payments, manage online inventories, and market their goods through social media. Telemedicine has made quality health consultations possible for patients hundreds of kilometers away from urban hospitals. Women-led Self-Help Groups (SHGs) use WhatsApp to coordinate microcredit and scale community entrepreneurship. For many, the digital leap has not just improved convenience—it has created dignity and agency.",
      "messageDateTimeCreated": "2025-06-21T13:12:48Z",
      "isEdited": false,
      "referenceMessageId": null,
      "messageSubDescription": "Bot described grassroots transformation",
      "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
    },
    {
      "messageId": "605",
      "messageType": "User",
      "messageAvatarSrc": "logo",
      "messageDescription": "That’s powerful. What about India's performance in global innovation or digital public infrastructure?",
      "messageDateTimeCreated": "2025-06-21T13:13:05Z",
      "isEdited": false,
      "referenceMessageId": null,
      "messageSubDescription": "User inquired about global position",
      "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
    },
    {
      "messageId": "606",
      "messageType": "Bot",
      "messageAvatarSrc": "logo",
      "messageDescription": "India now ranks among the top 40 nations in the Global Innovation Index. Its pioneering open digital public goods—like UPI, Aadhaar, and DigiLocker—have become global case studies. Countries in Africa and Southeast Asia are actively studying these frameworks to replicate their success. Startups like Zerodha, Byju's, and Ola have paved the way for a confident, product-first ecosystem. Backed by vibrant policy support, India’s innovation is now decentralized—coming equally from small towns and metros alike.",
      "messageDateTimeCreated": "2025-06-21T13:13:20Z",
      "isEdited": false,
      "referenceMessageId": null,
      "messageSubDescription": "Bot responded with global innovation commentary",
      "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
    },
    {
      "messageId": "607",
      "messageType": "User",
      "messageAvatarSrc": "logo",
      "messageDescription": "That decentralization sounds really exciting. Are there risks or challenges still being faced?",
      "messageDateTimeCreated": "2025-06-21T13:13:35Z",
      "isEdited": false,
      "referenceMessageId": null,
      "messageSubDescription": "User asking about ongoing bottlenecks",
      "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
    },
    {
      "messageId": "608",
      "messageType": "Bot",
      "messageAvatarSrc": "logo",
      "messageDescription": "Indeed. While progress is undeniable, challenges persist. Digital inequality is real—many regions still suffer from patchy internet or language barriers. There's also the issue of skilling keeping pace with automation. Even with high digital literacy, gaps remain in critical thinking and employability. Regulatory bottlenecks, fragmented policy execution, and environmental degradation in the race for urbanization are also part of the tightrope India walks.",
      "messageDateTimeCreated": "2025-06-21T13:13:50Z",
      "isEdited": false,
      "referenceMessageId": null,
      "messageSubDescription": "Bot balanced optimism with realities",
      "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
    },
    {
      "messageId": "609",
      "messageType": "User",
      "messageAvatarSrc": "logo",
      "messageDescription": "Fascinating insights. Thanks for articulating this so clearly.",
      "messageDateTimeCreated": "2025-06-21T13:14:04Z",
      "isEdited": false,
      "referenceMessageId": null,
      "messageSubDescription": "User expressed gratitude",
      "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
    },
    {
      "messageId": "610",
      "messageType": "Bot",
      "messageAvatarSrc": "logo",
      "messageDescription": "Always a pleasure, Aditya. India's journey is one of ambition, contradictions, and deep resilience. Let’s keep exploring.",
      "messageDateTimeCreated": "2025-06-21T13:14:15Z",
      "isEdited": false,
      "referenceMessageId": null,
      "messageSubDescription": "Bot wraps up with poetic reflection",
      "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
    }
  ]
  },
  {
    "conversationId": "af12accc-88b6-4af1-b3b0-7c43219312a2",
    "messages": [
      {
        "messageId": "701",
        "messageType": "User",
        "messageAvatarSrc": "logo",
        "messageDescription": "Can you give me a detailed overview of where AI stands in 2025—its maturity, applications, risks, and upcoming trends?",
        "messageDateTimeCreated": "2025-06-21T13:20:00Z",
        "isEdited": false,
        "referenceMessageId": null,
        "messageSubDescription": "User requested AI overview",
        "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
      },
      {
        "messageId": "702",
        "messageType": "Bot",
        "messageAvatarSrc": "logo",
        "messageDescription": "\n# 🌐 Artificial Intelligence in 2025\n\n## 📊 Global Adoption Status\nAI has matured into a foundational layer across multiple industries:\n\n### Top Domains by Adoption Rate (2025)\n| Sector              | AI Penetration | Example Application            |\n|---------------------|----------------|-------------------------------|\n| Healthcare          | 83%            | Predictive diagnostics         |\n| Finance             | 79%            | Fraud detection and modeling  |\n| Retail & E-commerce | 72%            | Personalization engines       |\n| Education           | 65%            | Adaptive learning platforms   |\n\n---\n\n## 🧠 Current Capabilities\n1. **Multimodal AI**: Seamlessly processes voice, image, and text inputs.\n2. **Agentic AI systems**: Models that complete tasks over time, with memory.\n3. **Explainable AI**: Interpretability embedded into outputs.\n\n---\n\n## ⚠️ Key Risks and Challenges\n- Bias amplification in decision-making\n- Hallucinations and misalignment\n- Over-dependence without robust regulation\n\n> *“AI will be more collaborative than replacement-driven.”* — [WEF Report, 2025](https://www.weforum.org/reports/)\n\n---\n\n## 🔮 Trends to Watch\n1. **Edge AI deployment**: Processing data locally for real-time inference.\n2. **Sovereign AI**: Nations building localized foundational models.\n3. **AI code agents**: Models writing and testing entire backend modules.\n\n---\n\n💡 **Fun Stat**: By mid-2025, AI is responsible for:\n- Writing ~23% of new software modules\n- Generating 38% of marketing visuals\n- Responding to over 50% of L1 customer queries\n\n---\n\n📚 Sources:\n- Stanford AI Index 2025: [aiindex.stanford.edu](https://aiindex.stanford.edu/)\n- World Economic Forum 2025 Insights\n\n",
        "messageDateTimeCreated": "2025-06-21T13:20:20Z",
        "isEdited": false,
        "referenceMessageId": null,
        "messageSubDescription": "Comprehensive markdown response",
        "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
      },
      {
        "messageId": "703",
        "messageType": "User",
        "messageAvatarSrc": "logo",
        "messageDescription": "Amazing. What about the role of open-source models?",
        "messageDateTimeCreated": "2025-06-21T13:20:40Z",
        "isEdited": false,
        "referenceMessageId": null,
        "messageSubDescription": "Question about open-source ecosystem",
        "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
      },
      {
        "messageId": "704",
        "messageType": "Bot",
        "messageAvatarSrc": "logo",
        "messageDescription": "\n## 🛠️ Open-Source LLM Ecosystem in 2025\n\nOpen-source has become critical for AI democratization. The most prominent models include:\n\n1. **Mistral and Mixtral (France)**\n2. **LLaMA-3 (Meta)**\n3. **Gemma (Google)**\n4. **Qwen-2 and InternLM (China)**\n\nThese models are widely used in fine-tuning enterprise assistants, hobby projects, and academic tools.\n\n> Over **47%** of startups in AI tooling now build on open weights.\n",
        "messageDateTimeCreated": "2025-06-21T13:21:00Z",
        "isEdited": false,
        "referenceMessageId": null,
        "messageSubDescription": "Markdown answer about LLMs",
        "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
      },
      {
        "messageId": "705",
        "messageType": "User",
        "messageAvatarSrc": "logo",
        "messageDescription": "And alignment progress? Are we closer to safety guarantees?",
        "messageDateTimeCreated": "2025-06-21T13:21:15Z",
        "isEdited": false,
        "referenceMessageId": null,
        "messageSubDescription": "Follow-up on alignment & safety",
        "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
      },
      {
        "messageId": "706",
        "messageType": "Bot",
        "messageAvatarSrc": "logo",
        "messageDescription": "\n## ✅ Safety & Alignment in 2025\n\n### Major Developments:\n- **RLHF v2** now includes ethical gradient optimization.\n- **Simulated AI Societies** used for stress testing multi-agent scenarios.\n- **AI watchdogs** mandated in EU and Japan under digital sovereignty laws.\n\nStill, *perfect alignment* is elusive. Major labs publish transparency reports quarterly.\n",
        "messageDateTimeCreated": "2025-06-21T13:21:35Z",
        "isEdited": false,
        "referenceMessageId": null,
        "messageSubDescription": "Safety protocols described",
        "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
      },
      {
        "messageId": "707",
        "messageType": "User",
        "messageAvatarSrc": "logo",
        "messageDescription": "Has India launched any domestic LLMs?",
        "messageDateTimeCreated": "2025-06-21T13:21:50Z",
        "isEdited": false,
        "referenceMessageId": null,
        "messageSubDescription": "Asking about India's contribution",
        "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
      },
      {
        "messageId": "708",
        "messageType": "Bot",
        "messageAvatarSrc": "logo",
        "messageDescription": "\n🇮🇳 **India’s Indigenous AI Efforts**\n\nIndia recently introduced:\n- **BharatGPT** by AI4Bharat (multilingual, low-resource optimized)\n- **Vaani** by IIT-Bombay for code and law domain tasks\n\nThey’ve focused on:\n- Inclusivity (11+ Indic languages)\n- Legal comprehension (Indian Penal Code corpus)\n- Support for low-bandwidth inference\n",
        "messageDateTimeCreated": "2025-06-21T13:22:10Z",
        "isEdited": false,
        "referenceMessageId": null,
        "messageSubDescription": "Bot celebrates India's AI entry",
        "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
      },
      {
        "messageId": "709",
        "messageType": "User",
        "messageAvatarSrc": "logo",
        "messageDescription": "That’s encouraging. Is there still room for solo developers to contribute meaningfully?",
        "messageDateTimeCreated": "2025-06-21T13:22:30Z",
        "isEdited": false,
        "referenceMessageId": null,
        "messageSubDescription": "User asking about indie contributors",
        "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
      },
      {
      "messageId": "710",
      "messageType": "Bot",
      "messageAvatarSrc": "logo",
      "messageDescription": "\n## 🧑‍💻 Indie Developer Impact in AI (2025)\n\nDespite the dominance of large labs, solo developers are thriving in the AI ecosystem:\n\n### 🚀 Contributions:\n1. **Model Adapters**: Over 45% of LoRA-style adapters on Hugging Face are authored by indie developers.\n2. **Tooling Frameworks**: Libraries like `langchain`, `llama-cpp`, and `autoeval` have community-driven forks improving flexibility.\n3. **Inference UX**: Lightweight runners like `Ollama`, `Exllama`, and `GPT4All` are community-crafted.\n\n---\n\n### 🌐 Collaboration Platforms\n- **[Hugging Face](https://huggingface.co)** for model sharing & fine-tuning\n- **[Weights & Biases](https://wandb.ai)** for experiment tracking\n- **[Kaggle](https://kaggle.com)** for competitions and data hacks\n\n> The rise of open weights has blurred the line between hobbyist and practitioner.\n\n🎯 Whether it's building assistants, AI art, or dataset refinement, individual creators now have the tools to match enterprise-level ambitions.\n",
      "messageDateTimeCreated": "2025-06-21T13:22:55Z",
      "isEdited": false,
      "referenceMessageId": null,
      "messageSubDescription": "Bot explains how solo devs are shaping the AI landscape",
      "messageAdditionalInfo": { "tableData": [], "chartData": [], "extra": {} }
      }
    ]
  }
]
